name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Test, Build and Deploy
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node-version: [ 16.x ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js with nvm
        run: |
          node -v
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
          nvm install 16
          nvm alias system 16
          nvm use system
          node -v
      - name: Install All and Build
        run: |
          node -v
          bash ./home/iotuser/startup/base.sh
          bash ./home/iotuser/startup/cedalo.sh install
        env:
          BU_USER: ${{ secrets.BU_USER }}
          BU_PASS: ${{ secrets.BU_PASS }}
          MU_USER: ${{ secrets.MU_USER }}
          MU_PASS: ${{ secrets.MU_PASS }}
      - name: Deploy
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ env.REMOTE_USER }}
          SOURCE: home/${{ env.REMOTE_USER }}/projects/cedalo_platform/management-center/src/backend/public
          TARGET: /home/${{ env.REMOTE_USER }}/projects/cedalo_platform/management-center/src/backend/public
